# Generated by Django 3.2.5 on 2021-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1Students',
            fields=[
                ('no_field', models.AutoField(db_column='No.', primary_key=True, serialize=False)),
                ('sid', models.IntegerField(db_column='sId')),
                ('f_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=25)),
                ('status', models.CharField(db_column='Status', max_length=45)),
                ('birthday', models.DateTimeField(db_column='Birthday')),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('contact_no_field', models.IntegerField(db_column='Contact No.')),
                ('course', models.CharField(db_column='Course', max_length=45)),
                ('year_and_section', models.CharField(db_column='Year and Section', max_length=45)),
            ],
            options={
                'db_table': 'app1_students',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
